import { NextUIProvider, Navbar, NavbarBrand } from "@nextui-org/react";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import NextTopLoader from 'nextjs-toploader';

import { auth } from "../lib/auth";
import Logo from "../lib/components/layout/logo";
import UserActions from "../lib/components/layout/user-actions";
import Menu from "../lib/components/layout/menu";

import "../globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Footer from "../lib/components/layout/footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth()

  return (
    <html lang="en">
      <head />
      <body className={`${inter.className} antialiased`}>
        <NextTopLoader
          showAtBottom={true} />

        <NextUIProvider>
          <main className="light">
            <Navbar maxWidth="full" style={{ backgroundColor: 'rgb(59, 130, 246)', color: 'white' }}  >
              <NavbarBrand className="md:flex-grow-0 md:min-w-[250px]">
                <Logo />
                <p className="font-bold text-inherit">EXPENSE MANAGER</p>
              </NavbarBrand>
              <Menu />
              <UserActions session={session} />
            </Navbar>
            <div className="container mx-auto py-10 h-full">
              {children}
            </div>
          </main>
        </NextUIProvider>
        <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}